application:
  version: 0.0.1
  title: Projeto para desenvolvimento de habilidades voltadas ao GitHub Actions e Kubernetes
spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  springdoc:
    writer-with-order-by-keys: true
    swagger-ui:
      path: /documentacao.html
      operationsSorter: method
      tagsSorter: alpha
    api-docs:
      path: /documentacao