application:
  version: 0.0.1
  title: Projeto para desenvolvimento de habilidades voltadas ao GitHub Actions e Kubernetes
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/actionsandkubernetes
    username: ${MYSQL_USER:}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  springdoc:
    writer-with-order-by-keys: true
    swagger-ui:
      path: /documentacao.html
      operationsSorter: method
      tagsSorter: alpha
    api-docs:
      path: /documentacao
server:
  port: 8080
  servlet:
    context-path: /api